version: '3'
services:
  master:
    image: mpi-image
    container_name: mpi_master
    networks:
      - mpi_network

  slave1:
    image: mpi-image
    container_name: mpi_slave1
    networks:
      - mpi_network

  slave2:
    image: mpi-image
    container_name: mpi_slave2
    networks:
      - mpi_network

networks:
  mpi_network:
    driver: bridge
